# Generated by Django 3.1.7 on 2021-03-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='isRecruiter',
        ),
        migrations.AddField(
            model_name='user',
            name='isRecruiter',
            field=models.BooleanField(default=False),
        ),
    ]
