# Generated by Django 3.1.7 on 2021-03-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210306_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetail',
            name='isverified',
        ),
    ]
